apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-b-production
  namespace: exam-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-b-production
  template:
    metadata:
      labels:
        app: portal-b-production
    spec:
      imagePullSecrets:
        - name: registry-credentials

      containers:
        - name: portal-b
          image: 192.168.10.23:5000/portal-b:1.0.4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: PORT
              value: "5000"

            - name: APP_ENV
              value: "production"

            - name: APP_VERSION
              value: 1.0.4

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: portal-b-secret
                  key: API_KEY

            - name: CONFIG_PATH
              value: "/app/config/config.json"

          volumeMounts:
            - name: app-config
              mountPath: /app/config
              readOnly: true

          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

      volumes:
        - name: app-config
          configMap:
            name: portal-b-config-production