apiVersion: v1
kind: Service
metadata:
  name: portal-b-production
  namespace: exam-2
spec:
  selector:
    app: portal-b-production
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30182
  type: NodePort